export const lightTheme = {
  background: "#ffffff",
  foreground: "#1f2937",
  card: "#ffffff",
  cardForeground: "#1f2937",
  border: "#e5e7eb",
  input: "#e5e7eb",
  primary: "#3b82f6",
  primaryForeground: "#ffffff",
  secondary: "#f3f4f6",
  secondaryForeground: "#1f2937",
  accent: "#f3f4f6",
  accentForeground: "#1f2937",
  destructive: "#ef4444",
  destructiveForeground: "#ffffff",
  muted: "#f3f4f6",
  mutedForeground: "#6b7280",
  success: "#10b981",
  successForeground: "#ffffff",
  warning: "#f59e0b",
  warningForeground: "#ffffff",
  info: "#3b82f6",
  infoForeground: "#ffffff",
}

export const darkTheme = {
  background: "#0f172a",
  foreground: "#f8fafc",
  card: "#1e293b",
  cardForeground: "#f8fafc",
  border: "#334155",
  input: "#334155",
  primary: "#3b82f6",
  primaryForeground: "#ffffff",
  secondary: "#1e293b",
  secondaryForeground: "#f8fafc",
  accent: "#1e293b",
  accentForeground: "#f8fafc",
  destructive: "#ef4444",
  destructiveForeground: "#ffffff",
  muted: "#1e293b",
  mutedForeground: "#94a3b8",
  success: "#10b981",
  successForeground: "#ffffff",
  warning: "#f59e0b",
  warningForeground: "#ffffff",
  info: "#3b82f6",
  infoForeground: "#ffffff",
}
